# k8s/osm2-records-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: osm2-records-service
  namespace: osm2
  labels:
    app: osm2-records-service
spec:
  selector:
    app: osm2-records-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
