package dk.ufst.bookkeeping.domain;

public enum EventType {
  DEBT_REGISTERED,
  PAYMENT_RECEIVED,
  INTEREST_ACCRUED,
  OFFSETTING_EXECUTED,
  WRITE_OFF,
  REFUND,
  UDLAEG_REGISTERED,
  UDLAEG_CORRECTED,
  CORRECTION,
  COVERAGE_REVERSED
}
